# Generated by Django 5.1.6 on 2025-02-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games_app', '0002_todo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo_list',
        ),
    ]
