# Generated by Django 5.1.6 on 2025-02-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games_app', '0003_alter_todo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='GameProjects.todo_list',
        ),
    ]
